const API = "http://localhost:8081";
export const API_ADMIN = `${API}/admin`;
export const API_STUDENT = `${API}/student`;
export const API_STUDENTDETAIL = `${API}/studentdetail`;
export const API_STUDENTMEDIA = `${API}/studentmedia`;
export const API_SCORE = `${API}/score`;
export const API_TEACHER = `${API}/teacher`;
export const API_TEACHERDETAIL = `${API}/teacherdetail`;
export const API_LESSON = `${API}/lesson`;
export const API_CLASSES = `${API}/classes`;
export const API_LAB = `${API}/lab`;
export const API_DEPARTMENT = `${API}/department`;
export const API_CHART = `${API}/chart`;
export default API;
